### ISSUE TITLE
Major Tasks Checklist

### ISSUE THREAD

**Issue by dreamingmind** [curlyjason/rci#9]
**User Facing**
- [ ] extend session life of add 'keep me logged in'
- [ ] develop front facing user management pages
- [ ] configure email transport
- [ ] plan the automated and elective email pattern

**Admin Facing**
- [ ] set up /admin url prefix routes
- [ ] bake /admin prefixed classes
